import os
import yaml
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from ultralytics import YOLO

# ==========================================
# 🎨 PLOT STYLING
# ==========================================
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Times New Roman']
plt.rcParams['font.size'] = 11
plt.rcParams['figure.dpi'] = 300

def plot_class_frequency(names, metrics, save_dir):
    print("→ Generating Class Frequency Plot...")
    try:
        # In YOLOv8, the robust way to get Ground Truth counts is via the Confusion Matrix
        # Summing the rows of the matrix gives the total instances per class (Ground Truth)
        matrix = metrics.confusion_matrix.matrix
        ground_truth_counts = matrix.sum(1)  # Sum across rows

        # Filter out background class if it exists in the matrix but not in names
        # (The matrix often has +1 dimension for background)
        if len(ground_truth_counts) > len(names):
            ground_truth_counts = ground_truth_counts[:len(names)]

        df = pd.DataFrame({
            "Class": list(names.values()),
            "Ground Truth Count": ground_truth_counts
        })
        
        plt.figure(figsize=(10, 6))
        sns.barplot(data=df, x="Class", y="Ground Truth Count", palette="viridis")
        plt.title("Class Frequency (Ground Truth Instances)", fontweight="bold")
        plt.xticks(rotation=45, ha='right')
        plt.grid(axis='y', linestyle='--', alpha=0.3)
        
        out = os.path.join(save_dir, "Class_Frequency.png")
        plt.tight_layout()
        plt.savefig(out)
        plt.close()
        print(f"   ✔ Saved: {out}")
    except Exception as e:
        print(f"   ❌ Failed Class Frequency: {e}")

def plot_precision_recall_curve(metrics, save_dir):
    print("→ Generating Precision–Recall Curve...")
    try:
        # Access the PR Curve data generated by YOLO (Recall on x, Precision on y)
        # metrics.box.curves[3] is typically the PR curve tuple
        if hasattr(metrics.box, 'curves') and len(metrics.box.curves) > 0:
            pr_data = metrics.box.curves[3] 
            
            plt.figure(figsize=(6, 6))
            plt.plot(pr_data[0], pr_data[1], color='#003366', linewidth=2)
            
            plt.title(f"Precision–Recall Curve (mAP@0.5={metrics.box.map50:.2f})", fontweight="bold")
            plt.xlabel("Recall")
            plt.ylabel("Precision")
            plt.grid(True, linestyle='--', alpha=0.5)
            
            out = os.path.join(save_dir, "Precision_Recall_Curve.png")
            plt.tight_layout()
            plt.savefig(out)
            plt.close()
            print(f"   ✔ Saved: {out}")
        else:
            print("   ⚠ PR Curve data not found (Ensure plots=True was used).")
    except Exception as e:
        print(f"   ❌ Failed PR Curve: {e}")

def plot_final_map(metrics, save_dir):
    print("→ Generating Final mAP Bar Graph...")
    try:
        # box.map is the mean Average Precision (50-95)
        map50_95 = metrics.box.map
        
        plt.figure(figsize=(5, 6))
        plt.bar(["Final mAP"], [map50_95], color='#2E86C1', width=0.4)
        plt.title("Final mAP (mAP50-95)", fontweight="bold")
        plt.ylabel("Score")
        plt.ylim(0, 1.0)
        plt.grid(axis='y', linestyle='--', alpha=0.3)
        
        # Add text on top
        plt.text(0, map50_95 + 0.02, f"{map50_95:.3f}", ha='center', fontweight='bold')

        out = os.path.join(save_dir, "Final_mAP.png")
        plt.tight_layout()
        plt.savefig(out)
        plt.close()
        print(f"   ✔ Saved: {out}")
    except Exception as e:
        print(f"   ❌ Failed mAP Plot: {e}")

def plot_class_precision_recall(names, metrics, save_dir):
    print("→ Generating Per-Class Precision & Recall Plots...")
    try:
        # Use metrics.box.p (Array) instead of metrics.box.mp (Float/Average)
        df = pd.DataFrame({
            "Class": list(names.values()),
            "Precision": metrics.box.p,
            "Recall": metrics.box.r
        })

        # Plot Precision
        plt.figure(figsize=(10, 5))
        sns.barplot(data=df, x="Class", y="Precision", palette="Blues_d")
        plt.title("Per-Class Precision", fontweight="bold")
        plt.xticks(rotation=45, ha='right')
        plt.ylim(0, 1.1)
        plt.grid(axis='y', linestyle='--', alpha=0.3)
        out = os.path.join(save_dir, "Class_Precision.png")
        plt.tight_layout()
        plt.savefig(out)
        plt.close()

        # Plot Recall
        plt.figure(figsize=(10, 5))
        sns.barplot(data=df, x="Class", y="Recall", palette="Reds_d")
        plt.title("Per-Class Recall", fontweight="bold")
        plt.xticks(rotation=45, ha='right')
        plt.ylim(0, 1.1)
        plt.grid(axis='y', linestyle='--', alpha=0.3)
        out2 = os.path.join(save_dir, "Class_Recall.png")
        plt.tight_layout()
        plt.savefig(out2)
        plt.close()
        
        print("   ✔ Saved precision & recall graphs")
    except Exception as e:
        print(f"   ❌ Failed Class P/R Plots: {e}")

def save_confusion_matrix(metrics, save_dir):
    print("→ Saving Confusion Matrix...")
    try:
        # YOLOv8 metrics object has the confusion matrix built-in
        # We can trigger the plot method on the confusion matrix object
        # It usually saves strictly to the run directory, but we can move it 
        # or just rely on the data.
        
        # Alternative: Manually plot using seaborn if you want strict control,
        # but Ultralytics does it well automatically if plots=True.
        # Here we will try to save the one explicitly.
        import shutil
        
        # Check if it was already generated in the save_dir (since we ran val(plots=True))
        possible_cm = os.path.join(metrics.save_dir, 'confusion_matrix.png')
        target_cm = os.path.join(save_dir, 'Confusion_Matrix.png')
        
        if os.path.exists(possible_cm):
            shutil.copy(possible_cm, target_cm)
            print("   ✔ Confusion Matrix Copied from runs folder")
        else:
            print("   ⚠ Confusion Matrix image not found in runs folder.")

    except Exception as e:
        print(f"   ⚠ Could not process confusion matrix: {e}")

def run_evaluation():
    # --- PATHS ---
    model_path = r"C:\Users\RUPIN\Documents\sign language\sign language - Copy\best.pt"
    dataset_dir = r"C:\Users\RUPIN\Documents\sign language\sign language - Copy\datasets"
    output_folder = r"C:\Users\RUPIN\Documents\sign language\IEEE_Graphs"
    
    os.makedirs(output_folder, exist_ok=True)

    print("🚀 Loading YOLOv8 Model...")
    model = YOLO(model_path)

    # Create temp YAML
    data_yaml = {
        'path': os.path.abspath(dataset_dir),
        'train': '.',
        'val': '.',
        'names': model.names
    }
    with open('temp_data.yaml', 'w') as f:
        yaml.dump(data_yaml, f)

    print("🚀 Running Validation...")
    # plots=True is CRITICAL to generate the curves and confusion matrix data
    metrics = model.val(data='temp_data.yaml', split='val', verbose=False, plots=True)

    print("\n📊 Generating Graphs...")
    
    plot_class_frequency(model.names, metrics, output_folder)
    plot_precision_recall_curve(metrics, output_folder)
    plot_final_map(metrics, output_folder)
    plot_class_precision_recall(model.names, metrics, output_folder)
    save_confusion_matrix(metrics, output_folder)

    print(f"\n✅ All Graphs Saved To: {output_folder}")

    if os.path.exists('temp_data.yaml'):
        os.remove('temp_data.yaml')

if __name__ == "__main__":
    run_evaluation()